on: [issues]

jobs:
  obs_helper:
    runs-on: ubuntu-latest
    steps:
      - name: Create Default Bucket on OBS
        uses: huaweicloud/obs-helper@v1.2.0
        id: create_default_bucket_on_obs
        with:
          access_key: ${{ secrets.ACCESSKEY }}
          secret_key: ${{ secrets.SECRETACCESSKEY }}
          region: cn-north-4
          operation_type: createbucket
          bucket_name: obs-lizy-20220702-4