on: [push]

jobs:
  obs_helper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Upload Folder To OBS
        uses: huaweicloud/obs-helper@v1.2.0
        id: upload_multi_files_to_obs
        with:
          access_key: ${{ secrets.ACCESSKEY }}
          secret_key: ${{ secrets.SECRETACCESSKEY }}
          bucket_name: obs-lizy20220702
          local_file_path: |
            ./resource/upload/folder1
            ./resource/upload/folder2
            ./resource/upload/file1.txt    
          obs_file_path: src/upload 
          operation_type: upload
          include_self_folder: true