on: [issues]

jobs:
  obs_helper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Upload File To OBS
        uses: huaweicloud/obs-helper@v1.2.0
        id: upload_file_to_obs
        with:
          access_key: ${{ secrets.ACCESSKEY }}
          secret_key: ${{ secrets.SECRETACCESSKEY }}
          region: ${region}
          bucket_name: ${bucket_name}
          local_file_path: ./resource/upload/file1.txt
          obs_file_path: src/upload/
          operation_type: upload